name: Unzip file

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          mkdir -p extracted
          unzip -o "duong/dan/proxy.zip" -d extracted

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add extracted
          git commit -m "Auto unzip file"
          git push
